### PR TITLE
closes #2

### LINKED ISSUE #2: Add nearest neighbour matching to simulations for revision

### PR DESCRIPTION
**Pull request by LukaszChrostowski**

### CODE REVIEW

**Comment by BERENZ** [comment]
@Kertoo Any comments? If not I will merge it.

@LukaszChrostowski I am not sure if this really closes #2. If I see correctly it does not include the proposed simulation

**Comment by LukaszChrostowski** [comment]
@BERENZ you are right, I've just added knn imputation to the simulations but did not take into account simulation proposals listed in #2

**Review by Kertoo — CHANGES_REQUESTED** [review]
The simulation runs of NN estimator do not include the V_2 component of variance (the same argument as for PMM i.e. `pmm_exact_se`) in `sim-appen-1-choose-k.R` (I think this simulation only makes sense with the "mini-bootstrap" variance computation), `sim-appen-2-varsel.R`, `sim-appen-4-positivity.R`, `sim-appen-5-multiplirobust.R` .

Simulation for main paper should also have both versions of NN with and without minibootstrap variance for comparison.

I also think that `sim-appen-3-nonparam.R` doesn't really need NN but if its already there just for comparison we should add "exact_se".

And as @BERENZ mentioned closing #2 would require adding simulation for when important covariates are missing. I think the first point on only one covariate is covered in main paper simulaition, while variable selection simulation covers the second point.

**Comment by BERENZ** [comment]
@LukaszChrostowski @Kertoo I will modify the main simulation to account for reviewer request after the merge.

**Pull request merged**
